export enum CLIENT_ERROR_CODE {
	BAD_REQUEST = 400,
	UNAUTHORIZED = 401,
	NOT_FOUND = 404,
	TOO_MANY_REQUESTS = 429
}

export enum SUCCESSFULL_CODE {
	OK = 200
}

export enum REDIRECT_CODE {
	TEMPORARY_REDIRECT = 307
}

export enum SERVER_ERROR_CODE {
	INTERNAL_SERVER_ERROR = 500
}
